### ISSUE TITLE
TypeScript import error in version 2.0.0

### ISSUE THREAD

**Issue by danoc** [matthewmueller/next-cookies#23]
Hello!

Just upgraded to 2.0.0 and am now getting this error:

```
Attempted import error: 'next-cookies' does not contain a default export (imported as 'cookies').
```

This is the import I'm using:

```js
import cookies from "next-cookies";
```

What are the breaking changes in this version?

Thanks!

**Comment by nfriedly** [comment]
Hi @danoc, sorry about that, I'm not entirely sure what happened. The API should have stayed the same, the change was to the underlying library, see #21. 

TypeScript isn't my strongest point, so if you want to take a look and see if there is anything obvious, that'd be appreciated.

In addition to the library change, the PR switched from having separate JavaScript files for the browser and node, to a single index.js file for both. (And added a bunch of test infrastructure.)

I didn't change the TypeScript typings because, like I said, I didn't think there was any API changes.

**Comment by danoc** [comment]
Hey @nfriedly, no worries! Thanks for the response. I'll post back here if I get the chance to dig into it. If not, perhaps someone else will stumble upon this and know the fix.

**Comment by UncleClapton** [comment]
FWIW, I'm getting this problem in a normal JS environment as well. Seems like module import syntax is broken with this release? I can only import using commonjs syntax like: `const cookies = require('next-cookies')`

**Comment by lemonadey** [comment]
I can confirm `import cookies from 'next-cookies'` is broken in vanilla JS next

**Comment by nfriedly** [comment]
I believe v2.0.1 should fix this. There's something funky going on where it's trying to use the cjs version of the dependency in node but the es6 version in the browser, and so in one case you need to use the default export, and in the other case there isn't one. I'm not entirely sure why.

So, this is a dumb fix, but it does seem to work:

https://github.com/matthewmueller/next-cookies/blob/ff11f46005e7f70fdf0319cb57c3e50e9c06f26f/index.js#L1-L4

Also, I restructured the test app to be completely standalone so that it would catch this problem and others like it.

Anyways, everyone please test v2.0.1 and confirm that it's working for you.

**Comment by lemonadey** [comment]
Works like a charm now.
Thanks for the quick fix.
