### ISSUE TITLE
Issue with reading a cookie

### ISSUE THREAD

**Issue by hellozuech** [matthewmueller/next-cookies#47]
When using NextCookie there appears to be a bug.

Issue with Reading cookies in ^2.0.3 on NPM

downgrade to ^1.1.3 works

Issue reading Req when attempting to read a cookie

**Comment by Gentatsu** [comment]
Get this issue as well. 

![image](https://user-images.githubusercontent.com/3910724/168629180-43aa6585-f0f9-46e7-9e4c-4babb8cb7e44.png)

**Comment by nfriedly** [comment]
I'd need to see your code to know for sure, but that stack trace indicates that next-cookies is being called directly by react without any of your code in-between - are you trying to use next-cookies as a high-order component? Because that won't work.

The call to next-cookies has to be inside of the [getInitialProps](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props) method (or [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) or [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)) so that you can pass in the context variable. [Example](https://github.com/matthewmueller/next-cookies#complete-example).

**Comment by Gentatsu** [comment]
I'm indeed not passing in the context. This was the case prior to upgrading to `2.0.3`, and it worked fine. I've migrated the codebase to use [js-cookie](https://www.npmjs.com/package/js-cookie) instead, and this seems to work fine inside HOCs.

**Comment by nfriedly** [comment]
Ok, that was your issue. Passing in context was always a required part of the API, but in 1.x the client code path didn't actually use it, so incorrect usage didn't always result in errors. In 2.x it's required for either client or server usage, so failing to provide it will always result in an error.

In either case, it should work inside of a HOC, it just isn't a HOC itself.

(I mostly just wanted to clarify those two points in case anyone else came along with a similar issue. If you're happy with js-cookie, then stick with that :)
